config/routes.rb
Rails.application.routes.draw do
  resources :deployments
  post '/deployments/add_service/:id', to: 'deployments#add_service'
  post '/deployments/update_service/:id', to: 'deployments#update_service'
  post '/deployments/remove_service/:id', to: 'deployments#remove_service'

  post '/deployments/deploy/:id', to: 'deployments#deploy', as: 'deploy'

  resources :versions
  post '/services/add_version/:id', to: 'services#add_version'

  resources :environments
  get '/environments/:id/remove_version/:version', to: 'environments#remove_version'

  resources :services
  post 'services/load_versions/:id', to: 'services#load_versions'

  get 'jobs/:name/build/:number', to: 'build#show'
  get 'jobs', to: 'jobs#index'
  get 'jobs/:id', to: 'jobs#show'

  resources :jenkins
end

app/models/jenkin.rb
class Jenkin < ApplicationRecord
  def jobs
    jobs = []
    names = client.job.list_all
    names.each do |name|
      jobs << self.job(name)
    end
    jobs
  end

  def job_names
    client.job.list_all
  end


  def job(name)
    Job.new name: name, job: client.job
  end

  def client
    @client = @client || JenkinsApi::Client.new(
      server_ip: self.server_ip,
      username: self.username,
      password: self.password
    )
    @client
  end
end

app/controllers/jenkins_controller.rb
class JenkinsController < ApplicationController
  before_action :set_jenkin, only: [:show, :edit, :update, :destroy]

  # GET /jenkins
  # GET /jenkins.json
  def index
    @jenkins = Jenkin.all
  end

  # GET /jenkins/1
  # GET /jenkins/1.json
  def show
  end

  # GET /jenkins/new
  def new
    @jenkin = Jenkin.new
  end

  # GET /jenkins/1/edit
  def edit
  end

  # POST /jenkins
  # POST /jenkins.json
  def create
    @jenkin = Jenkin.new(jenkin_params)

    respond_to do |format|
      if @jenkin.save
        format.html { redirect_to @jenkin, notice: 'Jenkin was successfully created.' }
        format.json { render :show, status: :created, location: @jenkin }
      else
        format.html { render :new }
        format.json { render json: @jenkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jenkins/1
  # PATCH/PUT /jenkins/1.json
  def update
    respond_to do |format|
      if @jenkin.update(jenkin_params)
        format.html { redirect_to @jenkin, notice: 'Jenkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @jenkin }
      else
        format.html { render :edit }
        format.json { render json: @jenkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jenkins/1
  # DELETE /jenkins/1.json
  def destroy
    @jenkin.destroy
    respond_to do |format|
      format.html { redirect_to jenkins_url, notice: 'Jenkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jenkin
      @jenkin = Jenkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jenkin_params
      params.require(:jenkin).permit(:server_ip, :username, :password)
    end
end

app/helpers/jenkins_helper.rb
module JenkinsHelper
end

app/views/jenkins/_form.html.erb
<%= form_with(model: jenkin, local: true) do |form| %>
  <% if jenkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jenkin.errors.count, "error") %> prohibited this jenkin from being saved:</h2>

      <ul>
      <% jenkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :server_ip %>
    <%= form.text_field :server_ip, id: :jenkin_server_ip %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :jenkin_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :jenkin_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jenkins/edit.html.erb
<h1>Editing Jenkin</h1>

<%= render 'form', jenkin: @jenkin %>

<%= link_to 'Show', @jenkin %> |
<%= link_to 'Back', jenkins_path %>

app/views/jenkins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jenkins</h1>

<table>
  <thead>
    <tr>
      <th>Server ip</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jenkins.each do |jenkin| %>
      <tr>
        <td><%= jenkin.server_ip %></td>
        <td><%= jenkin.username %></td>
        <td><%= jenkin.password %></td>
        <td><%= link_to 'Show', jenkin %></td>
        <td><%= link_to 'Edit', edit_jenkin_path(jenkin) %></td>
        <td><%= link_to 'Destroy', jenkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jenkin', new_jenkin_path %>

app/views/jenkins/new.html.erb
<h1>New Jenkin</h1>

<%= render 'form', jenkin: @jenkin %>

<%= link_to 'Back', jenkins_path %>

app/views/jenkins/show.html.erb
<div class="page-header">
  <%= link_to jenkin_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_jenkin_path(@jenkin), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show jenkin</h1>
</div>

<dl class="dl-horizontal">
  <dt>Server ip:</dt>
  <dd><%= @jenkin.server_ip %></dd>

  <dt>Username:</dt>
  <dd><%= @jenkin.username %></dd>

  <dt>Password:</dt>
  <dd><%= @jenkin.password %></dd>

</dl>