config/routes.rb
Rails.application.routes.draw do
  resources :deployments
  post '/deployments/add_service/:id', to: 'deployments#add_service'
  post '/deployments/update_service/:id', to: 'deployments#update_service'
  post '/deployments/remove_service/:id', to: 'deployments#remove_service'

  post '/deployments/deploy/:id', to: 'deployments#deploy', as: 'deploy'

  resources :versions
  post '/services/add_version/:id', to: 'services#add_version'

  resources :environments
  get '/environments/:id/remove_version/:version', to: 'environments#remove_version'

  resources :services
  post 'services/load_versions/:id', to: 'services#load_versions'

  get 'jobs/:name/build/:number', to: 'build#show'
  get 'jobs', to: 'jobs#index'
  get 'jobs/:id', to: 'jobs#show'

  resources :jenkins
end

app/models/environment.rb
class Environment < ApplicationRecord
  has_and_belongs_to_many :versions

  ##
  # Bump the environments version of a service. This method is to be called from
  # the Deployment class when a deployment is executed.
  #
  # @param [Service] service
  # @param [Version] version
  def bump_version(service, version)
    current = version? service
    self.versions.delete current if current
    self.versions << version
    self.save
  end

  ##
  # Determine the environments Version of the service.
  #
  # @param [Service] service
  # @returns [Version]
  def version?(service)
    versions = self.versions.select { |v| v.service.eql?(service) }
    return nil if versions.empty?
    versions.first
  end
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_environment, only: [:show, :edit, :update, :destroy, :remove_version]

  def remove_version
    version = Version.find(params[:version])

    respond_to do |format|
      if @environment.versions.delete version
        format.html { redirect_to @environment }
        format.json { render :show, status: :ok, location: @environment }
      else
        format.html { render :show }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /environments
  # GET /environments.json
  def index
    @environments = Environment.all
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
  end

  # GET /environments/new
  def new
    @environment = Environment.new
  end

  # GET /environments/1/edit
  def edit
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(environment_params)

    respond_to do |format|
      if @environment.save
        format.html { redirect_to @environment, notice: 'Environment was successfully created.' }
        format.json { render :show, status: :created, location: @environment }
      else
        format.html { render :new }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /environments/1
  # PATCH/PUT /environments/1.json
  def update
    respond_to do |format|
      if @environment.update(environment_params)
        format.html { redirect_to @environment, notice: 'Environment was successfully updated.' }
        format.json { render :show, status: :ok, location: @environment }
      else
        format.html { render :edit }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    @environment.destroy
    respond_to do |format|
      format.html { redirect_to environments_url, notice: 'Environment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment
      @environment = Environment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def environment_params
      params.require(:environment).permit(:name)
    end
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.erb
<%= form_for(@environment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @environment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@environment.errors.count, "error") %> prohibited this environment from being saved:</h4>

      <ul>
      <% @environment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>

  <%# Attaching Services %>
  <%= tag 'div', class: 'environment_services', data: { services: Service.all.map { |s| { name: s.name, id: s.id} } } %>
    <%# <div class="form-group"> %>
    <%#   <%= f.label 'name', class: "col-sm-2 control-label" %1> %>
    <%#   <div class="col-sm-10"> %>
    <%#     <%= f.collection_select 'name', Service.all, :id, :name, class: 'selectpicker job_selection' %1> %>
    <%#   </div> %>
    <%# </div> %>

<% end %>

app/views/environments/edit.html.erb
<div class="page-header">
  <%= link_to environments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @environment, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing environment</h1>
</div>

<%= render 'form' %>

app/views/environments/index.html.erb
<div class="page-header">
  <%= link_to new_environment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Environment
  <% end %>
  <h1>Listing environments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @environments) do |environment| %>
            <td><%= environment.name %></td>
            <td><%= link_to 'Show', environment %></td>
        <td><%= link_to 'Edit', edit_environment_path(environment) %></td>
        <td><%= link_to 'Destroy', environment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/environments/new.html.erb
<div class="page-header">
  <%= link_to environments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New environment</h1>
</div>

<%= render 'form' %>

app/views/environments/show.html.erb
<div class="page-header">
  <%= link_to environments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_environment_path(@environment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%= @environment.name %></h1>
</div>


<h3>Services</h3>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Version</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @environment.versions.each do |version| %>
        <tr>
          <td><%= version.service.name %></td>
          <td><%= version.name %></td>
          <td><%= link_to 'Show', version.service %></td>
          <td><%= link_to 'Remove', { controller: 'environments', action: 'remove_version', version: version.id, id: @environment.id } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>