config/routes.rb
Rails.application.routes.draw do
  resources :deployments
  post '/deployments/add_service/:id', to: 'deployments#add_service'
  post '/deployments/update_service/:id', to: 'deployments#update_service'
  post '/deployments/remove_service/:id', to: 'deployments#remove_service'

  post '/deployments/deploy/:id', to: 'deployments#deploy', as: 'deploy'

  resources :versions
  post '/services/add_version/:id', to: 'services#add_version'

  resources :environments
  get '/environments/:id/remove_version/:version', to: 'environments#remove_version'

  resources :services
  post 'services/load_versions/:id', to: 'services#load_versions'

  get 'jobs/:name/build/:number', to: 'build#show'
  get 'jobs', to: 'jobs#index'
  get 'jobs/:id', to: 'jobs#show'

  resources :jenkins
end

app/models/deployment.rb
class Deployment < ApplicationRecord
  belongs_to :environment
  has_and_belongs_to_many :versions
end

app/controllers/deployments_controller.rb
class DeploymentsController < ApplicationController
  include JenkinsControllerConcern

  before_action :set_deployment, only: [:show, :edit, :update, :destroy, :add_service, :remove_service, :update_service, :deploy]

  def deploy
    env = @deployment.environment
    @deployment.versions.each do |version|
      Rails.logger.debug "Bumping version of #{version.service.name} to #{version.name}"
      version.deploy environment: env, jenkins: load_jenkins
      env.bump_version version.service, version
    end
    @deployment.status = true
    @deployment.save
    redirect_to deployments_url(@deployment)
  end

  def update_service
    version = Version.find(service_params[:id])
    service = Service.find_by(name: service_params[:name])
    versions = @deployment.versions.select { |v| v.service == service }
    @deployment.versions.delete versions
    @deployment.versions << version
    @deployment.save
    redirect_to edit_deployment_url(@deployment)
  end

  ##
  # Action to add a service version from a deployment
  #
  def add_service
    service = Service.find(service_params[:id])
    if service.nil? || service.versions.empty?
      msg =  "No versions of #{service.name} available"
      Rails.logger.error msg
      link = "Please add versions to #{view_context.link_to(service.name, service_path(service))}"
      redirect_to edit_deployment_url(@deployment), flash: { error: "#{msg}, #{link}" }
    else
      version = service.versions.first
      @deployment.versions << version
      @deployment.save
      redirect_to edit_deployment_url(@deployment)
    end
  end

  ##
  # Action to remove a service version from a deployment
  #
  def remove_service
    service = Service.find(params[:service_id])
    version = Version.find(params[:version_id])
    @deployment.versions.delete(version)
    render :edit
  end

  # GET /deployments
  # GET /deployments.json
  def index
    @deployments = Deployment.all
  end

  # GET /deployments/1
  # GET /deployments/1.json
  def show
  end

  # GET /deployments/new
  def new
    @deployment = Deployment.new
  end

  # GET /deployments/1/edit
  def edit
  end

  # POST /deployments
  # POST /deployments.json
  def create
    @deployment = Deployment.new(deployment_params)

    respond_to do |format|
      if @deployment.save
        format.html { redirect_to @deployment, notice: 'Deployment was successfully created.' }
        format.json { render :show, status: :created, location: @deployment }
      else
        format.html { render :new }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deployments/1
  # PATCH/PUT /deployments/1.json
  def update
    respond_to do |format|
      if @deployment.update(deployment_params)
        services_params(@deployment).each do |service_name, version_name|
          version = Version.find_by(name: version_name)
          @deployment.versions << version if version
        end
        @deployment.save
        format.html { redirect_to @deployment, notice: 'Deployment was successfully updated.' }
        format.json { render :show, status: :ok, location: @deployment }
      else
        format.html { render :edit }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deployments/1
  # DELETE /deployments/1.json
  def destroy
    @deployment.destroy
    respond_to do |format|
      format.html { redirect_to deployments_url, notice: 'Deployment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def service_params
      params.require(:service).permit(:version, :id, :name)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_deployment
      @deployment = Deployment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deployment_params
      params.require(:deployment).permit(:environment_id, :name)
    end

    def services_params(deployment)
      params.require(:environment).permit(deployment.environment.versions.map { |v| v.service.name})
    end
end

app/helpers/deployments_helper.rb
module DeploymentsHelper
end

app/views/deployments/_form.html.erb
<%= form_for(@deployment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @deployment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@deployment.errors.count, "error") %> prohibited this deployment from being saved:</h4>

      <ul>
      <% @deployment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :environment_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :environment_id, Environment.all, :id, :name, {}, { class: 'selectpicker' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<h3>Services</h3>

<% @deployment.versions.each do |version| %>
  <%= form_for(version.service, url: { action: 'update_service' }, html: { class: "form-horizontal", role: "form", method: 'post' }) do |s| %>
    <div class="form-group">
      <label for="service" class="col-sm-1 control-label">Service: </label>
      <div class="col-sm-6">
        <%= s.text_field :name, id: :id, class: 'col-sm-12', readonly: true %>
      </div>
      <div class="col-sm-2">
        <%= s.collection_select :id, version.service.versions, :id, :name, { selected: version.id }, { class: 'selectpicker' } %>
      </div>
      <div class="col-sm-1">
        <%= link_to 'x', {:controller => 'deployments', :action => 'remove_service', service_id: version.service.id, version_id: version.id }, {:method => :post } %>
      </div>
      <div class="col-sm-1">
        <%= s.submit 'Save', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>


<% if @deployment.id %>
  <hr />
  <%# Add Service %>
  <%= form_for(:service, url: { action: 'add_service' }, html: { class: "form-horizontal", role: "form", method: 'post' }) do |s| %>
    <div class="form-group">
      <label for="service" class="col-sm-1 control-label">Service: </label>
      <div class="col-sm-6">
        <%= s.collection_select :id, Service.all, :id, :name, {}, { class: 'selectpicker' } %>
      </div>
      <div class="col-sm-1">
        <%= s.submit 'Add Service', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="form-group">
    <div class="col-md-12">
      <em>Must specify the deployment's environment before attaching services</em>
    </div>
  </div>
<% end %>

app/views/deployments/edit.html.erb
<div class="page-header">
  <%= link_to deployments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @deployment, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing deployment</h1>
</div>

<%= render 'form' %>

app/views/deployments/index.html.erb
<div class="page-header">
  <%= link_to new_deployment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Deployment
  <% end %>
  <h1>Listing deployments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Environment</th>
        <th>Status</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @deployments) do |deployment| %>
        <td><%= deployment.name %></td>
        <td><%= deployment.environment.name %></td>
        <td class="text-<%= deployment.status ? 'success' : 'failure' %>"><%= deployment.status ? 'Deployed' : 'Pending'%></td>
        <td><%= link_to 'Show', deployment %></td>
        <td><%= deployment.status ? 'Cannot Edit' : link_to('Edit', edit_deployment_path(deployment)) %></td>
        <td><%= deployment.status ? 'Cannot Destroy' :link_to('Destroy', deployment, method: :delete, data: { confirm: 'Are you sure?' }) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/deployments/new.html.erb
<div class="page-header">
  <%= link_to deployments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New deployment</h1>
</div>

<%= render 'form' %>

app/views/deployments/show.html.erb
<div class="page-header">
  <%= link_to deployments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_deployment_path(@deployment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end unless @deployment.status %>
  <h1>Deployment to <%= @deployment.environment.name %></h1>
  <h3 class="text-<%= @deployment.status ? 'success' : 'failure' %>">Status: <%= @deployment.status ? 'Deployed' : 'Pending'%></h3>
</div>


<%= link_to deploy_path(@deployment), method: :post, class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-pencil"></span>
  Deploy
<% end unless @deployment.status %>

<h3>Services</h3>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Version</th>
        <th>Deployment Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @deployment.versions.each do |version| %>
        <tr>
          <td><%= version.service.name %></td>
          <td><%= version.name %></td>
          <td class="text-<%= version.deployment_status(@deployment) %>"><%= version.deployment_status @deployment %></td>
          <td><%= link_to 'Edit', version.service %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if @deployment.versions.empty? %>
  <div class="form-group">
    <div class="col-md-12">
      <em><%= link_to 'Edit', edit_deployment_path(@deployment) %> deployment to add Services and Versions to Deploy</em>
    </div>
  </div>
<% end %>