config/routes.rb
Rails.application.routes.draw do
  resources :deployments
  post '/deployments/add_service/:id', to: 'deployments#add_service'
  post '/deployments/update_service/:id', to: 'deployments#update_service'
  post '/deployments/remove_service/:id', to: 'deployments#remove_service'

  post '/deployments/deploy/:id', to: 'deployments#deploy', as: 'deploy'

  resources :versions
  post '/services/add_version/:id', to: 'services#add_version'

  resources :environments
  get '/environments/:id/remove_version/:version', to: 'environments#remove_version'

  resources :services
  post 'services/load_versions/:id', to: 'services#load_versions'

  get 'jobs/:name/build/:number', to: 'build#show'
  get 'jobs', to: 'jobs#index'
  get 'jobs/:id', to: 'jobs#show'

  resources :jenkins
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Atlas</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
          Atlas
        </a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= current_class?(jenkins_path) %>"><%= link_to 'Jenkins', jenkins_path %></li>
          <li class="<%= current_class?(jobs_path) %>"><%= link_to 'Jobs', jobs_path %></li>
          <li class="<%= current_class?(services_path) %>"><%= link_to 'Services', services_path %></li>
          <li class="<%= current_class?(environments_path) %>"><%= link_to 'Environments', environments_path %></li>
          <li class="<%= current_class?(deployments_path) %>"><%= link_to 'Deployments', deployments_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == 'error' ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= raw msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>